MYSQL_URL: me.com
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
MYSQL_DB: ai_administer4
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PWD:
NACOS_ADDR: 127.0.0.1:8848

RABBITMQ_HOST: me.com
RABBITMQ_PORT: 5672
RABBITMQ_USER: guest
RABBITMQ_PWD: guest