MYSQL_URL: mysql:3306
MYSQL_USERNAME: root
MYSQL_PASSWORD: AiTest#1
MYSQL_DB: ai_administer
REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_PWD:
NACOS_ADDR: nacos:8848

RABBITMQ_HOST: rabbitmq
RABBITMQ_PORT: 5672
RABBITMQ_USER: guest
RABBITMQ_PWD: guest