version: "3.7"

services:
  redis:
    image: redis:6.0.6
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${ENV_DIR}/redis-data/config/redis.conf:/etc/redis/redis.conf
      - ${ENV_DIR}/redis-data/data:/data
    ports:
      - "${EXPOSE_REDIS}:6379"
  xxl_job:
    image: ai-platform:${SERVICE_VERSION_XXL_JOB}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    ports:
      - "${EXPOSE_XXL}:8080"
    environment:
      - spring.profiles.active=docker
  mysql:
    image: mysql:8.0.19
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --max_connections=5000
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=AiTest#1
      #      - MYSQL_DATABASE=xxx
      - MYSQL_PASSWORD=AiTest#1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ENV_DIR}/mysql-data/data:/var/lib/mysql
      - ${ENV_DIR}/mysql-data/config/my.cnf:/etc/mysql/my.cnf
      - ${ENV_DIR}/mysql-data/config/init:/docker-entrypoint-initdb.d
    ports:
      - "${EXPOSE_MYSQL}:3306"
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ${ENV_DIR}/nacos-data/data/standalone-logs/:/home/nacos/logs
      - ${ENV_DIR}/nacos-data/config/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "${EXPOSE_NACOS}:8848"
  sentinel:
    restart: always
    image: sentinel:1.8.2
    ports:
      - "${EXPOSE_SENTINEL}:8080"
  rabbitmq:
    restart: always
    image: rabbitmq:3.9-management
    ports:
      - "${EXPOSE_RABBITMQ_ADMIN}:15672"