version: "3.7"

services:
  rest_infra_api:
    image: boot-admin-starter:rest-infra-api-1.0.0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    environment:
      - spring.profiles.active=docker