version: "3.7"

services:
  nginx:
    image: nginx:1.21.3
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - ${ENV_DIR}/nginx-data/config/conf.d:/etc/nginx/conf.d
      - ${ENV_DIR}/nginx-data/config/certs:/etc/nginx/certs
      - ${ENV_DIR}/nginx-data/data/logs:/var/log/nginx
      - ${ENV_DIR}/nginx-data/data/html:/home/www
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"