version: "3.7"

services:
  gateway_service:
    image: ai-platform-gateway:${SERVICE_VERSION_GATEWAY}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    volumes:
    - ${ENV_DIR2}/gateway-service/data:/runner/data
  video_stream_service:
    image: ai-platform:${SERVICE_VERSION_VIDEO_STREAM}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    environment:
      - spring.profiles.active=docker
    depends_on:
      - gateway_service
  ai_kitchen:
    image: ai-platform:${SERVICE_VERSION_AI_KITCHEN}
    volumes:
      - /tmp:/tmp
    restart: always
    environment:
      - AI_LAZYLOAD=true
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]