version: "3.7"

services:
  nginx:
    image: nginx:1.21.3
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/certs:/etc/nginx/certs
      - ./nginxta/data/logs:/var/log/nginx
      - ./nginx/data/html:/home/www
    ports:
      - "${EXPOSE_PORT_NGINX}:80"
      - "${EXPOSE_PORT_NGINX_HTTPS}:443"
    depends_on:
      - rest_infra_api
  rest_infra_api:
    image: ${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    ports:
      - "${EXPOSE_PORT_REST_INFRA_API}:8080"
    environment:
      - spring.profiles.active=docker