version: "3.7"

services:
  video_stream_service:
    image: ai-platform:${SERVICE_VERSION_VIDEO_STREAM}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    environment:
      - spring.profiles.active=docker
    depends_on:
      - gateway_service