version: "3.7"

services:
  ai_kitchen:
    image: ai-platform:${SERVICE_VERSION_AI_KITCHEN}
    volumes:
      - /tmp:/tmp
    restart: always
    environment:
      - AI_LAZYLOAD=true
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
